name: build

on:
  push:
    branches:
      - "master"
      - "ci-*"
    tags:
      - "**"
  pull_request:

env:
  PY_COLORS: 1

jobs:
  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: python -m pip install -U build
      - name: Build sdist
        run: python -m build --sdist
      - name: List distributions
        run: ls -lR dist
      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist
      - name: Install sdist
        run: python -m pip install dist/*.tar.gz
      - name: Test
        run: python -m unittest discover tests

  build_wheels:
    name: Build wheels on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    needs:
      - build_sdist
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        # FIXME: need to add windows arm
        #        as well as aarch64/ppc64le/s390x
    env:
      CIBW_BUILD: cp313-*
      CIBW_TEST_COMMAND: python -m unittest discover {project}/tests
      CIBW_ARCHS_MACOS: "x86_64 arm64"
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: python -m pip install -U cibuildwheel
      - name: Download sdist
        uses: actions/download-artifact@v4
        with:
          name: sdist
          path: sdist
      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist sdist/*.tar.gz
        shell: bash
      - name: List distributions
        run: ls -lR dist
        shell: bash
      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.platform }}
          path: dist/*.whl
